<?php

declare(strict_types=1);

require_once 'includes/connection.php';
require_once 'includes/procurementAuthMiddleware.php';
require_once 'includes/procurementSupplierActivityReportService.php';

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

const PROCUREMENT_REPORT_NAVY = '0A1D29';
const PROCUREMENT_REPORT_NAVY_SOFT = '102D3A';
const PROCUREMENT_REPORT_TEAL = '18A79D';
const PROCUREMENT_REPORT_TEAL_DARK = '0B6D68';
const PROCUREMENT_REPORT_TEAL_SOFT = 'E8F7F5';
const PROCUREMENT_REPORT_BLUE_SOFT = 'EAF2FB';
const PROCUREMENT_REPORT_AMBER_SOFT = 'FFF5DE';
const PROCUREMENT_REPORT_RED_SOFT = 'FCEDED';
const PROCUREMENT_REPORT_GREEN_SOFT = 'E8F6EF';
const PROCUREMENT_REPORT_BORDER = 'D8E5E9';
const PROCUREMENT_REPORT_TEXT = '20343D';
const PROCUREMENT_REPORT_MUTED = '6B7F88';
const PROCUREMENT_REPORT_WHITE = 'FFFFFF';
const PROCUREMENT_REPORT_MAX_EXPORT_ROWS = 50000;

function procurementReportColumn(int $index): string
{
    return Coordinate::stringFromColumnIndex($index);
}

function procurementReportBrandSheet(
    Worksheet $sheet,
    string $title,
    string $subtitle,
    int $lastColumn,
    int $headerRow = 0
): void {
    $endColumn = procurementReportColumn($lastColumn);
    $sheet->setShowGridlines(false);
    $sheet->mergeCells("A1:{$endColumn}1");
    $sheet->mergeCells("A2:{$endColumn}2");
    $sheet->mergeCells("A3:{$endColumn}3");
    $sheet->setCellValue('A1', 'LAMBERT ELECTROMEC LIMITED  |  PROCUREDESK');
    $sheet->setCellValue('A2', $title);
    $sheet->setCellValue('A3', $subtitle);

    $sheet->getStyle("A1:{$endColumn}1")->applyFromArray([
        'font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => PROCUREMENT_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_TEAL_DARK]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $sheet->getStyle("A2:{$endColumn}2")->applyFromArray([
        'font' => ['bold' => true, 'size' => 20, 'color' => ['rgb' => PROCUREMENT_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_NAVY]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $sheet->getStyle("A3:{$endColumn}3")->applyFromArray([
        'font' => ['size' => 9, 'color' => ['rgb' => 'D7E7EC']],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_NAVY_SOFT]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $sheet->getRowDimension(1)->setRowHeight(23);
    $sheet->getRowDimension(2)->setRowHeight(34);
    $sheet->getRowDimension(3)->setRowHeight(22);

    if ($headerRow > 0) {
        procurementReportStyleHeader($sheet, $headerRow, $lastColumn);
        $sheet->freezePane('A' . ($headerRow + 1));
        $sheet->setAutoFilter("A{$headerRow}:{$endColumn}{$headerRow}");
    }

    $sheet->getPageSetup()
        ->setOrientation(PageSetup::ORIENTATION_LANDSCAPE)
        ->setPaperSize(PageSetup::PAPERSIZE_A4)
        ->setFitToWidth(1)
        ->setFitToHeight(0);
    $sheet->getPageMargins()->setTop(0.45)->setBottom(0.45)->setLeft(0.3)->setRight(0.3);
    $sheet->getHeaderFooter()->setOddFooter('&LGenerated by ProcureDesk&CPage &P of &N&R' . date('Y-m-d H:i'));
}

function procurementReportStyleHeader(Worksheet $sheet, int $headerRow, int $lastColumn): void
{
    $endColumn = procurementReportColumn($lastColumn);
    $sheet->getStyle("A{$headerRow}:{$endColumn}{$headerRow}")->applyFromArray([
        'font' => ['bold' => true, 'size' => 9, 'color' => ['rgb' => PROCUREMENT_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_TEAL_DARK]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
        'borders' => ['bottom' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['rgb' => PROCUREMENT_REPORT_TEAL]]],
    ]);
    $sheet->getRowDimension($headerRow)->setRowHeight(28);
}

function procurementReportStyleRows(Worksheet $sheet, int $firstRow, int $lastRow, int $lastColumn): void
{
    if ($lastRow < $firstRow) {
        return;
    }
    $endColumn = procurementReportColumn($lastColumn);
    $sheet->getStyle("A{$firstRow}:{$endColumn}{$lastRow}")->applyFromArray([
        'font' => ['size' => 9, 'color' => ['rgb' => PROCUREMENT_REPORT_TEXT]],
        'alignment' => ['vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
        'borders' => ['bottom' => ['borderStyle' => Border::BORDER_HAIR, 'color' => ['rgb' => PROCUREMENT_REPORT_BORDER]]],
    ]);
    for ($row = $firstRow; $row <= $lastRow; $row++) {
        $sheet->getRowDimension($row)->setRowHeight(24);
        if (($row - $firstRow) % 2 === 1) {
            $sheet->getStyle("A{$row}:{$endColumn}{$row}")->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB('F4F9FA');
        }
    }
}

function procurementReportSetWidths(Worksheet $sheet, array $widths): void
{
    foreach ($widths as $column => $width) {
        $sheet->getColumnDimension($column)->setWidth($width);
    }
}

function procurementReportMoneyFormat(Worksheet $sheet, string $range): void
{
    $sheet->getStyle($range)->getNumberFormat()->setFormatCode('#,##0.00;[Red]-#,##0.00;–');
    $sheet->getStyle($range)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
}

function procurementReportPercentFormat(Worksheet $sheet, string $range): void
{
    $sheet->getStyle($range)->getNumberFormat()->setFormatCode('0.##"%"');
    $sheet->getStyle($range)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
}

function procurementReportStatusStyle(Worksheet $sheet, string $column, int $firstRow, int $lastRow): void
{
    for ($row = $firstRow; $row <= $lastRow; $row++) {
        $status = strtolower(trim((string) $sheet->getCell($column . $row)->getValue()));
        if ($status === '') {
            continue;
        }
        $fill = PROCUREMENT_REPORT_BLUE_SOFT;
        $font = PROCUREMENT_REPORT_TEAL_DARK;
        if (str_contains($status, 'pending') || str_contains($status, 'processing')) {
            $fill = PROCUREMENT_REPORT_AMBER_SOFT;
            $font = '9A6500';
        } elseif (str_contains($status, 'paid') || str_contains($status, 'approved') || str_contains($status, 'account')) {
            $fill = PROCUREMENT_REPORT_GREEN_SOFT;
            $font = '2B966F';
        } elseif (str_contains($status, 'return') || str_contains($status, 'failed') || str_contains($status, 'cancel')) {
            $fill = PROCUREMENT_REPORT_RED_SOFT;
            $font = 'B84040';
        }
        $sheet->getStyle($column . $row)->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => $font]],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $fill]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
    }
}

function procurementReportLabelList(array $values, string $allLabel = 'All'): string
{
    $clean = array_values(array_filter(array_map(static fn($value): string => trim((string) $value), $values)));
    return $clean === [] ? $allLabel : implode(', ', $clean);
}

function procurementReportDateBasisLabel(string $basis): string
{
    return match ($basis) {
        'request_date' => 'Request Date',
        'received_date' => 'Received Date',
        'payment_date' => 'Payment Date',
        default => 'All Date Bases',
    };
}

function procurementReportScopeLabel(string $scope): string
{
    return match ($scope) {
        'local_final' => 'Local Final',
        'local_advance' => 'Local Advance',
        'fx_final' => 'FX Final',
        'fx_advance' => 'FX Advance',
        default => 'All Scopes',
    };
}

function procurementReportSupplierLabel(array $report): string
{
    $supplierId = (int) ($report['meta']['filters']['supplier_id'] ?? 0);
    if ($supplierId <= 0) {
        return 'All Suppliers';
    }
    $label = trim((string) ($report['meta']['supplier_label'] ?? ''));
    return $label !== '' ? $label : 'Selected Supplier';
}

function procurementReportBuildSummarySheet(Spreadsheet $spreadsheet, array $report, array $rows): void
{
    $sheet = $spreadsheet->getActiveSheet();
    $sheet->setTitle('Summary');
    $sheet->getTabColor()->setRGB(PROCUREMENT_REPORT_TEAL);
    $filters = $report['meta']['filters'] ?? [];
    $dateFrom = $filters['date_from'] ?? null;
    $dateTo = $filters['date_to'] ?? null;
    $period = ($dateFrom || $dateTo)
        ? (($dateFrom ?: 'Beginning') . ' to ' . ($dateTo ?: 'Present'))
        : 'All Dates';
    procurementReportBrandSheet(
        $sheet,
        'SUPPLIER ACTIVITY REPORT',
        procurementReportSupplierLabel($report) . '  •  ' . $period . '  •  ' . number_format(count($rows)) . ' transactions',
        7,
        0
    );

    $sheet->mergeCells('A5:G5');
    $sheet->setCellValue('A5', 'REPORT FILTERS');
    $sheet->getStyle('A5:G5')->applyFromArray([
        'font' => ['bold' => true, 'size' => 10, 'color' => ['rgb' => PROCUREMENT_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_TEAL_SOFT]],
        'borders' => ['bottom' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => PROCUREMENT_REPORT_BORDER]]],
    ]);

    $filterRows = [
        ['Supplier', procurementReportSupplierLabel($report), 'Period', $period],
        ['Scope', procurementReportScopeLabel((string) ($filters['scope'] ?? 'all')), 'Date Basis', procurementReportDateBasisLabel((string) ($filters['date_basis'] ?? 'all'))],
        ['Workflow Status', procurementReportLabelList((array) ($filters['status'] ?? [])), 'Payment Status', procurementReportLabelList((array) ($filters['payment_status'] ?? []))],
        ['Currency', strtoupper((string) ($filters['currency'] ?? 'ALL')) === 'ALL' ? 'All Currencies' : strtoupper((string) $filters['currency']), 'Search', trim((string) ($filters['search'] ?? '')) ?: 'None'],
    ];
    $sheet->fromArray($filterRows, null, 'A6');
    foreach ([6, 7, 8, 9] as $row) {
        $sheet->mergeCells("B{$row}:C{$row}");
        $sheet->mergeCells("E{$row}:G{$row}");
        $sheet->getStyle("A{$row}:G{$row}")->applyFromArray([
            'font' => ['size' => 9, 'color' => ['rgb' => PROCUREMENT_REPORT_TEXT]],
            'alignment' => ['vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
            'borders' => ['bottom' => ['borderStyle' => Border::BORDER_HAIR, 'color' => ['rgb' => PROCUREMENT_REPORT_BORDER]]],
        ]);
        $sheet->getStyle("A{$row}")->getFont()->setBold(true)->getColor()->setRGB(PROCUREMENT_REPORT_MUTED);
        $sheet->getStyle("D{$row}")->getFont()->setBold(true)->getColor()->setRGB(PROCUREMENT_REPORT_MUTED);
    }

    $counts = $report['summary']['counts'] ?? [];
    $sheet->mergeCells('A11:G11');
    $sheet->setCellValue('A11', 'ACTIVITY SNAPSHOT');
    $sheet->getStyle('A11:G11')->applyFromArray([
        'font' => ['bold' => true, 'size' => 10, 'color' => ['rgb' => PROCUREMENT_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_BLUE_SOFT]],
    ]);
    $countHeaders = ['Total Requests', 'Approved', 'With Accounts', 'Paid', 'Outstanding', 'Returned'];
    $countValues = [
        (int) ($counts['total_requests'] ?? 0),
        (int) ($counts['approved'] ?? 0),
        (int) ($counts['with_accounts'] ?? 0),
        (int) ($counts['paid'] ?? 0),
        (int) ($counts['outstanding'] ?? 0),
        (int) ($counts['returned'] ?? 0),
    ];
    for ($i = 0; $i < 6; $i++) {
        $column = procurementReportColumn($i + 1);
        $sheet->setCellValue("{$column}12", $countHeaders[$i]);
        $sheet->setCellValue("{$column}13", $countValues[$i]);
        $sheet->getStyle("{$column}12:{$column}13")->applyFromArray([
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $i === 4 ? PROCUREMENT_REPORT_AMBER_SOFT : PROCUREMENT_REPORT_TEAL_SOFT]],
            'borders' => ['outline' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => PROCUREMENT_REPORT_BORDER]]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
        ]);
        $sheet->getStyle("{$column}12")->getFont()->setBold(true)->setSize(8)->getColor()->setRGB(PROCUREMENT_REPORT_MUTED);
        $sheet->getStyle("{$column}13")->getFont()->setBold(true)->setSize(14)->getColor()->setRGB(PROCUREMENT_REPORT_NAVY);
    }

    $sheet->mergeCells('A15:G15');
    $sheet->setCellValue('A15', 'FINANCIAL POSITION BY CURRENCY');
    $sheet->getStyle('A15:G15')->applyFromArray([
        'font' => ['bold' => true, 'size' => 10, 'color' => ['rgb' => PROCUREMENT_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_TEAL_SOFT]],
    ]);
    $headers = ['Currency', 'Requests', 'Procurement Value', 'Payable', 'Paid', 'Outstanding', 'WHT'];
    $sheet->fromArray($headers, null, 'A16');
    procurementReportStyleHeader($sheet, 16, 7);
    $rowNumber = 17;
    foreach (($report['summary']['currencies'] ?? []) as $currency) {
        $sheet->fromArray([
            $currency['currency'] ?? 'UNKNOWN',
            (int) ($currency['request_count'] ?? 0),
            (float) ($currency['procurement_value'] ?? 0),
            (float) ($currency['payable'] ?? 0),
            (float) ($currency['paid'] ?? 0),
            (float) ($currency['outstanding'] ?? 0),
            (float) ($currency['wht'] ?? 0),
        ], null, 'A' . $rowNumber++);
    }
    $lastRow = max(17, $rowNumber - 1);
    procurementReportStyleRows($sheet, 17, $lastRow, 7);
    procurementReportMoneyFormat($sheet, "C17:G{$lastRow}");
    $sheet->getStyle("A17:A{$lastRow}")->getFont()->setBold(true)->getColor()->setRGB(PROCUREMENT_REPORT_TEAL_DARK);

    $agingTitleRow = $lastRow + 2;
    $agingHeaderRow = $agingTitleRow + 1;
    $agingFirstRow = $agingHeaderRow + 1;
    $sheet->mergeCells("A{$agingTitleRow}:G{$agingTitleRow}");
    $sheet->setCellValue("A{$agingTitleRow}", 'OUTSTANDING AGING BY CURRENCY');
    $sheet->getStyle("A{$agingTitleRow}:G{$agingTitleRow}")->applyFromArray([
        'font' => ['bold' => true, 'size' => 10, 'color' => ['rgb' => PROCUREMENT_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => PROCUREMENT_REPORT_AMBER_SOFT]],
    ]);
    $sheet->fromArray(['Currency', '0–30 Days', '31–60 Days', '61–90 Days', '90+ Days', 'Total Outstanding'], null, 'A' . $agingHeaderRow);
    procurementReportStyleHeader($sheet, $agingHeaderRow, 6);
    $agingRow = $agingFirstRow;
    foreach (($report['summary']['currencies'] ?? []) as $currency) {
        $aging = (array) ($currency['aging'] ?? []);
        $sheet->fromArray([
            $currency['currency'] ?? 'UNKNOWN',
            (float) ($aging['0_30'] ?? 0),
            (float) ($aging['31_60'] ?? 0),
            (float) ($aging['61_90'] ?? 0),
            (float) ($aging['90_plus'] ?? 0),
            (float) ($currency['outstanding'] ?? 0),
        ], null, 'A' . $agingRow++);
    }
    $agingLastRow = max($agingFirstRow, $agingRow - 1);
    procurementReportStyleRows($sheet, $agingFirstRow, $agingLastRow, 6);
    procurementReportMoneyFormat($sheet, "B{$agingFirstRow}:F{$agingLastRow}");
    $sheet->getStyle("A{$agingFirstRow}:A{$agingLastRow}")->getFont()->setBold(true)->getColor()->setRGB(PROCUREMENT_REPORT_TEAL_DARK);
    $noteRow = $agingLastRow + 1;
    $sheet->mergeCells("A{$noteRow}:G{$noteRow}");
    $sheet->setCellValue("A{$noteRow}", 'Aging uses the Account received date where available, otherwise the originating request date. Currencies are never combined.');
    $sheet->getStyle("A{$noteRow}:G{$noteRow}")->applyFromArray([
        'font' => ['italic' => true, 'size' => 8, 'color' => ['rgb' => PROCUREMENT_REPORT_MUTED]],
        'alignment' => ['wrapText' => true],
    ]);

    procurementReportSetWidths($sheet, ['A' => 20, 'B' => 18, 'C' => 20, 'D' => 20, 'E' => 20, 'F' => 22, 'G' => 18]);
    $sheet->getPageSetup()->setPrintArea("A1:G{$noteRow}");
}

function procurementReportBuildTransactionSheet(Spreadsheet $spreadsheet, string $title, array $rows, string $subtitle): void
{
    $sheet = $spreadsheet->createSheet();
    $safeTitle = substr($title, 0, 31);
    $sheet->setTitle($safeTitle);
    $sheet->getTabColor()->setRGB(PROCUREMENT_REPORT_TEAL);

    $headers = [
        'Date', 'PO / Purchase No.', 'Request No.', 'Supplier', 'Project', 'Scope', 'Invoice', 'Currency',
        'Procurement Value', 'Payable', 'Paid', 'Outstanding', 'WHT', 'Advance %', 'Workflow Status',
        'Payment Status', 'Account Status', 'PO Status', 'Officer', 'Received Date', 'Payment Date',
        'Aging Date', 'Age (Days)'
    ];
    procurementReportBrandSheet($sheet, strtoupper($title), $subtitle, count($headers), 6);
    $sheet->fromArray($headers, null, 'A6');

    $rowNumber = 7;
    foreach ($rows as $row) {
        $reference = trim((string) ($row['po_number'] ?? ''))
            ?: (trim((string) ($row['purchase_number'] ?? '')) ?: (string) ($row['request_number'] ?? ''));
        $project = trim((string) ($row['project_code'] ?? ''));
        $projectName = trim((string) ($row['project_name'] ?? ''));
        if ($project === '') {
            $project = $projectName;
        } elseif ($projectName !== '' && strcasecmp($project, $projectName) !== 0) {
            $project .= ' — ' . $projectName;
        }
        $sheet->fromArray([
            $row['request_date'] ?? null,
            $reference,
            $row['request_number'] ?? null,
            $row['supplier_name'] ?? 'Supplier not recorded',
            $project ?: null,
            $row['scope'] ?? null,
            $row['invoice_number'] ?? null,
            $row['currency'] ?? 'UNKNOWN',
            (float) ($row['procurement_value'] ?? 0),
            (float) ($row['payable_amount'] ?? 0),
            (float) ($row['paid_amount'] ?? 0),
            (float) ($row['outstanding_amount'] ?? 0),
            (float) ($row['wht_amount'] ?? 0),
            $row['advance_percentage'] === null ? null : (float) $row['advance_percentage'],
            $row['status'] ?? null,
            $row['payment_status'] ?? null,
            $row['account_status'] ?? null,
            $row['po_status'] ?? null,
            $row['officer'] ?? null,
            $row['received_date'] ?? null,
            $row['payment_date'] ?? null,
            $row['aging_date'] ?? null,
            (int) ($row['age_days'] ?? 0),
        ], null, 'A' . $rowNumber++);
    }

    $lastRow = max(7, $rowNumber - 1);
    procurementReportStyleRows($sheet, 7, $lastRow, count($headers));
    procurementReportMoneyFormat($sheet, "I7:M{$lastRow}");
    procurementReportPercentFormat($sheet, "N7:N{$lastRow}");
    procurementReportStatusStyle($sheet, 'O', 7, $lastRow);
    procurementReportStatusStyle($sheet, 'P', 7, $lastRow);
    procurementReportStatusStyle($sheet, 'Q', 7, $lastRow);
    $sheet->getStyle("H7:H{$lastRow}")->applyFromArray([
        'font' => ['bold' => true, 'color' => ['rgb' => PROCUREMENT_REPORT_TEAL_DARK]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
    ]);
    procurementReportSetWidths($sheet, [
        'A' => 14, 'B' => 24, 'C' => 21, 'D' => 30, 'E' => 30, 'F' => 15, 'G' => 18, 'H' => 11,
        'I' => 19, 'J' => 18, 'K' => 18, 'L' => 18, 'M' => 17, 'N' => 12, 'O' => 19, 'P' => 18,
        'Q' => 18, 'R' => 17, 'S' => 24, 'T' => 16, 'U' => 16, 'V' => 16, 'W' => 12,
    ]);
    $sheet->getPageSetup()->setPrintArea("A1:W{$lastRow}");
    $sheet->getPageSetup()->setRowsToRepeatAtTopByStartAndEnd(1, 6);
}

try {
    if (strtoupper((string) ($_SERVER['REQUEST_METHOD'] ?? 'GET')) !== 'GET') {
        jsonResponse(['status' => 'Failed', 'message' => 'Method not allowed.'], 405);
    }

    $user = procurementRequireAnyPermission($conn, procurementSupplierActivityReportPermissionCodes());
    $reportQuery = $_GET;
    $reportQuery['page'] = 1;
    $reportQuery['limit'] = 1;
    $report = procurementSupplierActivityReport($conn, $user, $reportQuery);
    $total = (int) ($report['meta']['total'] ?? 0);
    if ($total > PROCUREMENT_REPORT_MAX_EXPORT_ROWS) {
        throw new RuntimeException(
            'The filtered report contains more than ' . number_format(PROCUREMENT_REPORT_MAX_EXPORT_ROWS) . ' rows. Narrow the filters before exporting.',
            422
        );
    }

    $visibleScopes = procurementSupplierActivityReportVisibleScopes($user);
    $filters = procurementSupplierActivityReportPrepareFilters($_GET, $visibleScopes);
    $base = procurementSupplierActivityReportBaseSql($filters['request_types']);
    $filtered = procurementSupplierActivityReportBuildWhere($filters);
    $types = $base['types'] . $filtered['types'];
    $params = array_merge($base['params'], $filtered['params']);
    $derived = '(' . $base['sql'] . ') report';
    $rows = procurementSupplierActivityReportFetchAll(
        $conn,
        "SELECT report.* FROM {$derived} WHERE {$filtered['sql']} ORDER BY report.request_date DESC, report.created_at DESC, report.canonical_id DESC LIMIT ?",
        $types . 'i',
        array_merge($params, [PROCUREMENT_REPORT_MAX_EXPORT_ROWS])
    );
    $rows = array_map('procurementSupplierActivityReportSerializeRow', $rows);

    if (!class_exists(Spreadsheet::class)) {
        throw new RuntimeException('Supplier Activity Excel export requires PhpSpreadsheet.', 500);
    }

    $spreadsheet = new Spreadsheet();
    $spreadsheet->getProperties()
        ->setCreator('ProcureDesk')
        ->setCompany('Lambert Electromec Limited')
        ->setTitle('Supplier Activity Report')
        ->setSubject(procurementReportSupplierLabel($report))
        ->setDescription('Filtered ProcureDesk supplier activity with currency-separated financial summaries.');

    procurementReportBuildSummarySheet($spreadsheet, $report, $rows);
    $subtitle = procurementReportSupplierLabel($report) . '  •  ' . number_format(count($rows)) . ' filtered transactions';
    procurementReportBuildTransactionSheet($spreadsheet, 'All Transactions', $rows, $subtitle);

    $byCurrency = [];
    foreach ($rows as $row) {
        $currency = strtoupper(trim((string) ($row['currency'] ?? ''))) ?: 'UNKNOWN';
        $byCurrency[$currency][] = $row;
    }
    if (count($byCurrency) > 1) {
        foreach ($byCurrency as $currency => $currencyRows) {
            procurementReportBuildTransactionSheet(
                $spreadsheet,
                preg_replace('/[^A-Z0-9 _-]/i', '', $currency) ?: 'Currency',
                $currencyRows,
                procurementReportSupplierLabel($report) . '  •  ' . $currency . '  •  ' . number_format(count($currencyRows)) . ' transactions'
            );
        }
    }

    $spreadsheet->setActiveSheetIndex(0);
    $supplierSlug = preg_replace('/[^A-Za-z0-9]+/', '-', procurementReportSupplierLabel($report));
    $supplierSlug = trim((string) $supplierSlug, '-') ?: 'All-Suppliers';
    $dateFrom = (string) ($report['meta']['filters']['date_from'] ?? '');
    $dateTo = (string) ($report['meta']['filters']['date_to'] ?? '');
    $periodSlug = $dateFrom !== '' || $dateTo !== ''
        ? (($dateFrom ?: 'Beginning') . '-to-' . ($dateTo ?: 'Present'))
        : 'All-Dates';
    $filename = 'ProcureDesk-Supplier-Activity-' . $supplierSlug . '-' . $periodSlug . '.xlsx';

    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: private, no-store, max-age=0');
    header('X-Content-Type-Options: nosniff');
    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    $spreadsheet->disconnectWorksheets();
    exit;
} catch (Throwable $error) {
    $status = (int) $error->getCode();
    if ($status < 400 || $status > 599) {
        $status = 500;
    }
    if ($status >= 500) {
        error_log('ProcureDesk Supplier Activity Excel export error: ' . $error->getMessage());
    }
    jsonResponse([
        'status' => 'Failed',
        'message' => $status >= 500 ? 'Unable to export Supplier Activity Report.' : $error->getMessage(),
    ], $status);
}
