<?php

declare(strict_types=1);

require_once __DIR__ . '/cashReportHelpers.php';

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

const CASH_REPORT_NAVY = '0A1D29';
const CASH_REPORT_NAVY_SOFT = '102D3A';
const CASH_REPORT_TEAL = '18A79D';
const CASH_REPORT_TEAL_DARK = '0B6D68';
const CASH_REPORT_TEAL_SOFT = 'E8F7F5';
const CASH_REPORT_BLUE_SOFT = 'EAF2FB';
const CASH_REPORT_AMBER = 'E9A62A';
const CASH_REPORT_AMBER_SOFT = 'FFF5DE';
const CASH_REPORT_RED = 'D65C5C';
const CASH_REPORT_RED_SOFT = 'FCEDED';
const CASH_REPORT_GREEN = '2B966F';
const CASH_REPORT_GREEN_SOFT = 'E8F6EF';
const CASH_REPORT_BORDER = 'D8E5E9';
const CASH_REPORT_TEXT = '20343D';
const CASH_REPORT_MUTED = '6B7F88';
const CASH_REPORT_WHITE = 'FFFFFF';

function cashExcelColumn(int $index): string
{
    return Coordinate::stringFromColumnIndex($index);
}

function cashExcelTransactionLabel(string $type): string
{
    $labels = [
        'CASH_RECEIPT' => 'Additional cash received',
        'OPENING_BALANCE' => 'Opening balance',
        'DIRECT_DISBURSEMENT' => 'Direct cash disbursement',
        'IOU_DISBURSEMENT' => 'IOU / cash advance',
        'CASH_RETURN' => 'IOU retirement cash returned',
        'REIMBURSEMENT' => 'IOU reimbursement',
        'MUTILATED_CASH_SET_ASIDE' => 'Mutilated cash classified',
        'MUTILATED_CASH_REPLACEMENT' => 'Bank replacement of mutilated cash',
        'MUTILATED_CASH_BANK_RETURN' => 'Mutilated cash returned to bank',
        'REVERSAL' => 'Controlled reversal',
    ];

    $normalized = strtoupper($type);
    return $labels[$normalized] ?? ucwords(strtolower(str_replace('_', ' ', $normalized)));
}

function cashExcelBrandSheet(
    Worksheet $sheet,
    string $title,
    string $subtitle,
    string $period,
    int $lastColumn,
    int $headerRow,
    bool $landscape = true
): void {
    $endColumn = cashExcelColumn($lastColumn);
    $sheet->setShowGridlines(false);
    $sheet->mergeCells("A1:{$endColumn}1");
    $sheet->mergeCells("A2:{$endColumn}2");
    $sheet->mergeCells("A3:{$endColumn}3");
    $sheet->setCellValue('A1', 'ACCTLAB  |  CASH DESK');
    $sheet->setCellValue('A2', $title);
    $sheet->setCellValue('A3', $subtitle . '  •  ' . $period);

    $sheet->getStyle("A1:{$endColumn}1")->applyFromArray([
        'font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => CASH_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_TEAL_DARK]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $sheet->getStyle("A2:{$endColumn}2")->applyFromArray([
        'font' => ['bold' => true, 'size' => 20, 'color' => ['rgb' => CASH_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_NAVY]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $sheet->getStyle("A3:{$endColumn}3")->applyFromArray([
        'font' => ['size' => 9, 'color' => ['rgb' => 'D7E7EC']],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_NAVY_SOFT]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $sheet->getRowDimension(1)->setRowHeight(23);
    $sheet->getRowDimension(2)->setRowHeight(34);
    $sheet->getRowDimension(3)->setRowHeight(22);

    if ($headerRow > 0) {
        cashExcelStyleHeader($sheet, $headerRow, $lastColumn);
        $sheet->freezePane('A' . ($headerRow + 1));
        $sheet->setAutoFilter("A{$headerRow}:{$endColumn}{$headerRow}");
    }

    $sheet->getPageSetup()
        ->setOrientation($landscape ? PageSetup::ORIENTATION_LANDSCAPE : PageSetup::ORIENTATION_PORTRAIT)
        ->setPaperSize(PageSetup::PAPERSIZE_A4)
        ->setFitToWidth(1)
        ->setFitToHeight(0);
    $sheet->getPageMargins()->setTop(0.45)->setBottom(0.45)->setLeft(0.35)->setRight(0.35);
    $sheet->getHeaderFooter()->setOddFooter('&LGenerated by AcctLab&CPage &P of &N&R' . date('Y-m-d H:i'));
}

function cashExcelStyleHeader(Worksheet $sheet, int $headerRow, int $lastColumn): void
{
    $endColumn = cashExcelColumn($lastColumn);
    $sheet->getStyle("A{$headerRow}:{$endColumn}{$headerRow}")->applyFromArray([
        'font' => ['bold' => true, 'size' => 9, 'color' => ['rgb' => CASH_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_TEAL_DARK]],
        'alignment' => ['horizontal' => Alignment::HORIZONTAL_LEFT, 'vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
        'borders' => ['bottom' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['rgb' => CASH_REPORT_TEAL]]],
    ]);
    $sheet->getRowDimension($headerRow)->setRowHeight(28);
}

function cashExcelStyleRows(Worksheet $sheet, int $firstRow, int $lastRow, int $lastColumn): void
{
    if ($lastRow < $firstRow) {
        return;
    }

    $endColumn = cashExcelColumn($lastColumn);
    $sheet->getStyle("A{$firstRow}:{$endColumn}{$lastRow}")->applyFromArray([
        'font' => ['size' => 9, 'color' => ['rgb' => CASH_REPORT_TEXT]],
        'alignment' => ['vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => true],
        'borders' => [
            'bottom' => ['borderStyle' => Border::BORDER_HAIR, 'color' => ['rgb' => CASH_REPORT_BORDER]],
        ],
    ]);

    for ($row = $firstRow; $row <= $lastRow; $row++) {
        $sheet->getRowDimension($row)->setRowHeight(23);
        if (($row - $firstRow) % 2 === 1) {
            $sheet->getStyle("A{$row}:{$endColumn}{$row}")->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB('F4F9FA');
        }
    }
}

function cashExcelMoneyFormat(Worksheet $sheet, string $range): void
{
    $sheet->getStyle($range)->getNumberFormat()->setFormatCode('#,##0.00;[Red]-#,##0.00;–');
    $sheet->getStyle($range)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
}

function cashExcelSetWidths(Worksheet $sheet, array $widths): void
{
    foreach ($widths as $column => $width) {
        $sheet->getColumnDimension($column)->setWidth($width);
    }
}

function cashExcelStatusStyle(Worksheet $sheet, string $column, int $firstRow, int $lastRow): void
{
    for ($row = $firstRow; $row <= $lastRow; $row++) {
        $status = strtoupper((string) $sheet->getCell($column . $row)->getValue());
        if ($status === '') {
            continue;
        }
        $fill = CASH_REPORT_BLUE_SOFT;
        $font = CASH_REPORT_TEAL_DARK;
        if (in_array($status, ['PENDING', 'PENDING_RETURN', 'OVERDUE', 'PARTIAL', 'PARTIALLY_RETIRED'], true)) {
            $fill = CASH_REPORT_AMBER_SOFT;
            $font = '9A6500';
        } elseif (in_array($status, ['RETURNED', 'REPLACED', 'RECEIVED', 'CLOSED', 'ACTIVE'], true)) {
            $fill = CASH_REPORT_GREEN_SOFT;
            $font = CASH_REPORT_GREEN;
        } elseif (in_array($status, ['REVERSED', 'ARCHIVED', 'FAILED'], true)) {
            $fill = CASH_REPORT_RED_SOFT;
            $font = CASH_REPORT_RED;
        }
        $sheet->getStyle($column . $row)->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => $font]],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $fill]],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);
    }
}

function cashExcelMetricCard(Worksheet $sheet, string $range, string $labelCell, string $valueCell, string $label, float $value, string $fill): void
{
    [$start, $end] = Coordinate::rangeBoundaries($range);
    $startColumn = cashExcelColumn((int) $start[0]);
    $endColumn = cashExcelColumn((int) $end[0]);
    $startRow = (int) $start[1];
    $endRow = (int) $end[1];
    $sheet->mergeCells("{$startColumn}{$startRow}:{$endColumn}{$startRow}");
    $sheet->mergeCells("{$startColumn}" . ($startRow + 1) . ":{$endColumn}{$endRow}");
    $sheet->setCellValue($labelCell, $label);
    $sheet->setCellValue($valueCell, $value);
    $sheet->getStyle($range)->applyFromArray([
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $fill]],
        'borders' => ['outline' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => CASH_REPORT_BORDER]]],
    ]);
    $sheet->getStyle($labelCell)->applyFromArray([
        'font' => ['bold' => true, 'size' => 8, 'color' => ['rgb' => CASH_REPORT_MUTED]],
        'alignment' => ['vertical' => Alignment::VERTICAL_TOP],
    ]);
    $sheet->getStyle($valueCell)->applyFromArray([
        'font' => ['bold' => true, 'size' => 15, 'color' => ['rgb' => CASH_REPORT_NAVY]],
        'alignment' => ['vertical' => Alignment::VERTICAL_BOTTOM, 'horizontal' => Alignment::HORIZONTAL_LEFT],
    ]);
    cashExcelMoneyFormat($sheet, $valueCell);
}

function cashExcelSubmissionDescription(array $transaction): string
{
    $activity = cashExcelTransactionLabel((string) ($transaction['transaction_type'] ?? ''));
    $person = trim((string) ($transaction['person_name'] ?? ''));
    $detail = '';
    foreach (['category_name', 'reason', 'description'] as $field) {
        $candidate = trim((string) ($transaction[$field] ?? ''));
        if ($candidate !== '') {
            $detail = $candidate;
            break;
        }
    }

    $parts = [];
    if ($person !== '') {
        $parts[] = $person;
    }
    if ($detail !== '' && strcasecmp($detail, $person) !== 0) {
        $parts[] = $detail;
    }

    $description = $parts === [] ? $activity : implode(' — ', $parts) . ' · ' . $activity;
    if (!($transaction['affects_balance'] ?? true)) {
        $type = strtoupper((string) ($transaction['transaction_type'] ?? ''));
        $amount = 'NGN ' . number_format((float) ($transaction['amount'] ?? 0), 2, '.', ',');
        $description .= $type === 'MUTILATED_CASH_REPLACEMENT'
            ? ' · ' . $amount . ' restored to usable cash; cashbook balance unchanged'
            : ' · ' . $amount . ' classified as mutilated; cashbook balance unchanged';
    }
    return $description;
}

function cashExcelBuildSubmissionSheet(
    Worksheet $sheet,
    array $report,
    string $accountLabel,
    string $periodLabel
): void {
    $sheet->setTitle('Daily Cash Report');
    $sheet->getTabColor()->setRGB(CASH_REPORT_TEAL);
    cashExcelBrandSheet($sheet, 'DAILY CASH REPORT', $accountLabel, $periodLabel, 5, 0, false);
    $sheet->setCellValue('A1', 'LAMBERT ELECTROMEC LIMITED  |  CASH DESK');

    $sheet->mergeCells('A5:E5');
    $sheet->setCellValue('A5', 'CASH MOVEMENT STATEMENT');
    $sheet->getStyle('A5:E5')->applyFromArray([
        'font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => CASH_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_TEAL_SOFT]],
        'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['bottom' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => CASH_REPORT_BORDER]]],
    ]);
    $sheet->getRowDimension(5)->setRowHeight(25);

    $headers = ['Date', 'Description', 'Amount In', 'Amount Out', 'Balance'];
    $sheet->fromArray($headers, null, 'A6');
    cashExcelStyleHeader($sheet, 6, count($headers));

    $rowNumber = 7;
    $sheet->fromArray([
        $report['period']['start_date'],
        'Balance brought forward',
        null,
        null,
        (float) $report['summary']['opening_balance'],
    ], null, 'A' . $rowNumber++);

    foreach ($report['transactions'] as $transaction) {
        $sheet->fromArray([
            $transaction['transaction_date'],
            cashExcelSubmissionDescription($transaction),
            ($transaction['affects_balance'] ?? true) && $transaction['direction'] === 'IN' ? $transaction['amount'] : null,
            ($transaction['affects_balance'] ?? true) && $transaction['direction'] === 'OUT' ? $transaction['amount'] : null,
            $transaction['running_balance'],
        ], null, 'A' . $rowNumber++);
    }

    $lastMovementRow = max(7, $rowNumber - 1);
    cashExcelStyleRows($sheet, 7, $lastMovementRow, 5);
    cashExcelMoneyFormat($sheet, 'C7:E' . $lastMovementRow);
    $sheet->getStyle('A7:E7')->applyFromArray([
        'font' => ['bold' => true, 'color' => ['rgb' => CASH_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_BLUE_SOFT]],
    ]);
    $sheet->getStyle('C7:C' . $lastMovementRow)->getFont()->getColor()->setRGB(CASH_REPORT_GREEN);
    $sheet->getStyle('D7:D' . $lastMovementRow)->getFont()->getColor()->setRGB(CASH_REPORT_RED);
    $sheet->getStyle('E7:E' . $lastMovementRow)->getFont()->setBold(true)->getColor()->setRGB(CASH_REPORT_TEAL_DARK);

    $totalRow = $lastMovementRow + 1;
    $sheet->mergeCells("A{$totalRow}:B{$totalRow}");
    $sheet->setCellValue("A{$totalRow}", 'TOTAL MOVEMENT / CLOSING BALANCE');
    $sheet->setCellValue("C{$totalRow}", (float) $report['summary']['total_cash_in']);
    $sheet->setCellValue("D{$totalRow}", (float) $report['summary']['total_cash_out']);
    $sheet->setCellValue("E{$totalRow}", (float) $report['summary']['closing_balance']);
    $sheet->getStyle("A{$totalRow}:E{$totalRow}")->applyFromArray([
        'font' => ['bold' => true, 'size' => 10, 'color' => ['rgb' => CASH_REPORT_WHITE]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_NAVY]],
        'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['top' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['rgb' => CASH_REPORT_TEAL]]],
    ]);
    $sheet->getStyle("C{$totalRow}:E{$totalRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
    cashExcelMoneyFormat($sheet, "C{$totalRow}:E{$totalRow}");
    $sheet->getStyle("C{$totalRow}:E{$totalRow}")->getFont()->getColor()->setRGB(CASH_REPORT_WHITE);
    $sheet->getRowDimension($totalRow)->setRowHeight(27);

    $noteRow = $totalRow + 2;
    $sheet->mergeCells("A{$noteRow}:E{$noteRow}");
    $sheet->setCellValue(
        "A{$noteRow}",
        'Note: Mutilated cash is shown as a tagged reclassification. It does not change the report balance; it reduces only the usable cash available for payment until bank resolution.'
    );
    $sheet->getStyle("A{$noteRow}:E{$noteRow}")->applyFromArray([
        'font' => ['italic' => true, 'size' => 8, 'color' => ['rgb' => '8A6410']],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_AMBER_SOFT]],
        'alignment' => ['wrapText' => true, 'vertical' => Alignment::VERTICAL_CENTER],
        'borders' => ['outline' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'EBCB87']]],
    ]);
    $sheet->getRowDimension($noteRow)->setRowHeight(32);

    cashExcelSetWidths($sheet, ['A' => 15, 'B' => 55, 'C' => 18, 'D' => 18, 'E' => 19]);
    $sheet->freezePane('A7');
    $sheet->setAutoFilter('A6:E6');
    $sheet->getPageSetup()->setPrintArea("A1:E{$noteRow}");
    $sheet->getPageSetup()->setRowsToRepeatAtTopByStartAndEnd(1, 6);
}

try {
    cashRequireMethod('GET');
    $user = cashCurrentUser();
    $account = cashResolveAccount($conn, $user, cashRequestAccountId());
    [$startDate, $endDate] = cashReportRange($user);
    $exportType = strtolower(trim((string) ($_GET['report_type'] ?? 'full')));
    if (!in_array($exportType, ['full', 'submission'], true)) {
        throw new InvalidArgumentException('Unsupported Cash Desk report type.', 422);
    }
    $report = cashBuildReportData($conn, $user, $account, $startDate, $endDate, 50000);

    if (!class_exists(Spreadsheet::class)) {
        throw new RuntimeException('Cash report export requires PhpSpreadsheet.', 500);
    }

    $spreadsheet = new Spreadsheet();
    $spreadsheet->getProperties()
        ->setCreator('AcctLab')
        ->setCompany('Lambert Electromec Limited')
        ->setTitle('Cash Desk Report')
        ->setSubject($startDate . ' to ' . $endDate)
        ->setDescription('Daily cash submission, cash position, cashbook, IOU, receipt, daily closure and mutilated cash report.');

    $periodLabel = $startDate === $endDate
        ? 'Report date ' . date('d M Y', strtotime($startDate))
        : 'Period ' . date('d M Y', strtotime($startDate)) . ' to ' . date('d M Y', strtotime($endDate));
    $accountLabel = $report['account']['account_name'] . ' (' . $report['account']['account_code'] . ' · ' . $report['account']['currency'] . ')';
    $position = $report['cash_position'];
    $summary = $report['summary'];

    // Share-ready daily cash report matching the established management submission format.
    $submissionSheet = $spreadsheet->getActiveSheet();
    cashExcelBuildSubmissionSheet($submissionSheet, $report, $accountLabel, $periodLabel);

    if ($exportType === 'full') {
    // Cash Position: polished version of the supplied manual cash summary.
    $positionSheet = $spreadsheet->createSheet();
    $positionSheet->setTitle('Cash Position');
    cashExcelBrandSheet($positionSheet, 'CASH POSITION REPORT', $accountLabel, $periodLabel, 8, 0, true);
    $positionSheet->getTabColor()->setRGB(CASH_REPORT_TEAL);

    cashExcelMetricCard($positionSheet, 'A5:B7', 'A5', 'A6', 'OPENING USABLE CASH', (float) $position['opening_balance'], CASH_REPORT_BLUE_SOFT);
    cashExcelMetricCard($positionSheet, 'C5:D7', 'C5', 'C6', 'USABLE CASH ADDED', (float) $position['total_usable_inflows'], CASH_REPORT_GREEN_SOFT);
    cashExcelMetricCard($positionSheet, 'E5:F7', 'E5', 'E6', 'USABLE CASH REDUCED', (float) $position['total_outflows'], CASH_REPORT_RED_SOFT);
    cashExcelMetricCard($positionSheet, 'G5:H7', 'G5', 'G6', 'CLOSING USABLE CASH', (float) $position['closing_usable_balance'], CASH_REPORT_TEAL_SOFT);
    $positionSheet->getRowDimension(5)->setRowHeight(22);
    $positionSheet->getRowDimension(6)->setRowHeight(28);
    $positionSheet->getRowDimension(7)->setRowHeight(12);

    $positionSheet->setCellValue('A9', 'CASH MOVEMENT RECONCILIATION');
    $positionSheet->mergeCells('A9:D9');
    $positionSheet->getStyle('A9:D9')->applyFromArray([
        'font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => CASH_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_TEAL_SOFT]],
        'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
    ]);
    $positionSheet->fromArray(['Movement', 'Reference', 'Usable Increase', 'Usable Reduction'], null, 'A10');
    cashExcelStyleHeader($positionSheet, 10, 4);
    $movementRows = [
        ['Balance brought forward', 'BAL B/F', (float) $position['opening_balance'], null],
        ['Additional cash received', 'CASH RECEIPT', (float) $position['additional_cash'], null],
        ['IOU retirement / cash returned', 'RETIREMENT', (float) $position['iou_retirement_cash'], null],
        ['Clean cash exchanged for mutilated notes', 'MUTILATED REPLACEMENT', (float) $position['mutilated_cash_replacements'], null],
        ['Controlled reversals increasing cash', 'REVERSALS IN', (float) $position['reversals_in'], null],
        ['Direct cash disbursements', 'DIRECT EXPENSE', null, (float) $position['direct_disbursements']],
        ['IOU / cash advances issued', 'IOU ADVANCE', null, (float) $position['iou_advances']],
        ['IOU reimbursements paid', 'REIMBURSEMENT', null, (float) $position['reimbursements_paid']],
        ['Mutilated cash reclassified for bank return', 'MUTILATED CASH RESERVE', null, (float) $position['mutilated_cash_set_aside']],
        ['Mutilated cash returned without replacement', 'TOTAL CASH REDUCED; USABLE CASH UNCHANGED', null, null],
        ['Controlled reversals reducing cash', 'REVERSALS OUT', null, (float) $position['reversals_out']],
    ];
    $positionSheet->fromArray($movementRows, null, 'A11');
    cashExcelStyleRows($positionSheet, 11, 21, 4);
    cashExcelMoneyFormat($positionSheet, 'C11:D21');
    $positionSheet->setCellValue('A22', 'Closing usable cash');
    $positionSheet->setCellValue('C22', (float) $position['closing_usable_balance']);
    $positionSheet->setCellValue('A23', 'Pending mutilated cash reserve');
    $positionSheet->setCellValue('C23', (float) $position['pending_mutilated_cash']);
    $positionSheet->setCellValue('A24', 'TOTAL ACCOUNTED PHYSICAL CASH');
    $positionSheet->setCellValue('C24', (float) $position['total_accounted_cash']);
    $positionSheet->mergeCells('A22:B22');
    $positionSheet->mergeCells('A23:B23');
    $positionSheet->mergeCells('A24:B24');
    foreach ([22 => CASH_REPORT_TEAL_SOFT, 23 => CASH_REPORT_AMBER_SOFT, 24 => CASH_REPORT_NAVY] as $row => $fill) {
        $fontColor = $row === 24 ? CASH_REPORT_WHITE : CASH_REPORT_NAVY;
        $positionSheet->getStyle("A{$row}:D{$row}")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => $fontColor]],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $fill]],
            'borders' => ['top' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => CASH_REPORT_BORDER]]],
        ]);
    }
    cashExcelMoneyFormat($positionSheet, 'C22:C24');

    $positionSheet->setCellValue('A26', 'DETAILED CASH MOVEMENT REGISTER');
    $positionSheet->mergeCells('A26:H26');
    $positionSheet->getStyle('A26:H26')->applyFromArray([
        'font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => CASH_REPORT_NAVY]],
        'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => CASH_REPORT_TEAL_SOFT]],
    ]);
    $positionHeaders = ['Date', 'Particulars', 'Reference', 'Cash In', 'Disbursement', 'Mutilated Set Aside', 'Usable Balance', 'Notes'];
    $positionSheet->fromArray($positionHeaders, null, 'A27');
    cashExcelStyleHeader($positionSheet, 27, count($positionHeaders));
    $positionRow = 28;
    foreach ($report['transactions'] as $transaction) {
        $type = strtoupper((string) $transaction['transaction_type']);
        $isMutilated = $type === 'MUTILATED_CASH_SET_ASIDE';
        $isReplacement = $type === 'MUTILATED_CASH_REPLACEMENT';
        $isBankReturn = $type === 'MUTILATED_CASH_BANK_RETURN';
        $positionSheet->fromArray([
            $transaction['transaction_date'],
            cashExcelTransactionLabel($type) . ($transaction['person_name'] ? ' · ' . $transaction['person_name'] : ''),
            $transaction['transaction_reference'],
            ((($transaction['affects_balance'] ?? true) && $transaction['direction'] === 'IN') || $isReplacement) ? $transaction['amount'] : null,
            (($transaction['affects_balance'] ?? true) && $transaction['direction'] === 'OUT' && !$isMutilated && !$isBankReturn) ? $transaction['amount'] : null,
            $isMutilated ? $transaction['amount'] : null,
            $transaction['running_usable_balance'] ?? $transaction['running_balance'],
            $transaction['category_name'] ?: ($transaction['reason'] ?: $transaction['description']),
        ], null, 'A' . $positionRow);
        $positionRow++;
    }
    cashExcelStyleRows($positionSheet, 28, max(28, $positionRow - 1), 8);
    cashExcelMoneyFormat($positionSheet, 'D28:G' . max(28, $positionRow - 1));
    $positionSheet->freezePane('A28');
    $positionSheet->setAutoFilter('A27:H27');
    cashExcelSetWidths($positionSheet, ['A' => 13, 'B' => 34, 'C' => 24, 'D' => 15, 'E' => 15, 'F' => 18, 'G' => 16, 'H' => 34]);

    // Report summary.
    $summarySheet = $spreadsheet->createSheet();
    $summarySheet->setTitle('Report Summary');
    $summarySheet->getTabColor()->setRGB('4385C4');
    cashExcelBrandSheet($summarySheet, 'REPORT SUMMARY', $accountLabel, $periodLabel, 3, 6, false);
    $summarySheet->fromArray(['Metric', 'Value', 'Interpretation'], null, 'A6');
    $summaryRows = [
        ['Opening usable balance', $position['opening_balance'], 'Spendable cash before the selected period'],
        ['Additional cash received', $summary['cash_received'], 'Top-ups and cash inflows'],
        ['IOU cash returned', $summary['cash_returned'], 'Retirement cash returned to the desk'],
        ['Mutilated cash replacements', $summary['mutilated_cash_replaced'], 'Clean notes exchanged; no change to total cash balance'],
        ['Direct disbursements', $summary['direct_disbursements'], 'Immediate expenses paid in cash'],
        ['IOU advances', $summary['iou_advances'], 'Cash advances awaiting retirement'],
        ['Reimbursements paid', $summary['reimbursements_paid'], 'Additional cash paid after IOU retirement'],
        ['Mutilated cash classified', $summary['mutilated_cash_set_aside'], 'Unusable notes reclassified without changing the cashbook balance'],
        ['Mutilated cash returned to bank', $summary['mutilated_cash_returned_to_bank'] ?? 0, 'Actual cash leaving the Cash Desk without immediate replacement'],
        ['Total cash in', $summary['total_cash_in'], 'All posted inflows'],
        ['Total cash out', $summary['total_cash_out'], 'All balance-affecting posted outflows'],
        ['Net movement', $summary['net_movement'], 'Cash in less cash out'],
        ['Closing cash balance', $summary['closing_balance'], 'Cashbook balance before the pending mutilated reserve'],
        ['Pending mutilated reserve', $report['mutilated_summary']['pending_amount'], 'Notes held separately for bank return'],
        ['Total accounted physical cash', $position['total_accounted_cash'], 'Closing cash balance including pending mutilated notes'],
        ['Transaction count', $summary['transaction_count'], 'Ledger entries in the selected period'],
        ['Open IOUs', $report['iou_summary']['open_count'], 'IOUs not yet fully settled'],
        ['Outstanding IOU value', $report['iou_summary']['outstanding_value'], 'Value still under retirement'],
        ['Pending receipts', $report['receipt_summary']['pending_count'], 'Transactions awaiting documentation'],
    ];
    $summarySheet->fromArray($summaryRows, null, 'A7');
    $summaryLastRow = 6 + count($summaryRows);
    cashExcelStyleRows($summarySheet, 7, $summaryLastRow, 3);
    cashExcelMoneyFormat($summarySheet, 'B7:B' . $summaryLastRow);
    cashExcelSetWidths($summarySheet, ['A' => 31, 'B' => 18, 'C' => 48]);

    // Detailed Cashbook.
    $cashbook = $spreadsheet->createSheet();
    $cashbook->setTitle('Cashbook');
    $cashbook->getTabColor()->setRGB(CASH_REPORT_TEAL);
    $cashbookHeaders = ['Date', 'Reference', 'Activity', 'Direction', 'Recipient / Source', 'Reason', 'Description', 'Category', 'Cash In', 'Cash Out', 'Running Balance', 'IOU Ref.', 'IOU Status', 'Receipt Status', 'Recorded By', 'Recorded At'];
    cashExcelBrandSheet($cashbook, 'DETAILED CASHBOOK', $accountLabel, $periodLabel, count($cashbookHeaders), 6, true);
    $cashbook->fromArray($cashbookHeaders, null, 'A6');
    $rowNumber = 7;
    foreach ($report['transactions'] as $transaction) {
        $cashbook->fromArray([
            $transaction['transaction_date'], $transaction['transaction_reference'], cashExcelTransactionLabel((string) $transaction['transaction_type']),
            $transaction['direction'], $transaction['person_name'], $transaction['reason'], $transaction['description'], $transaction['category_name'],
            ($transaction['affects_balance'] ?? true) && $transaction['direction'] === 'IN' ? $transaction['amount'] : null,
            ($transaction['affects_balance'] ?? true) && $transaction['direction'] === 'OUT' ? $transaction['amount'] : null,
            $transaction['running_balance'], $transaction['iou_reference'], $transaction['iou_status'], $transaction['receipt_status'],
            $transaction['created_by_email'], $transaction['created_at'],
        ], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($cashbook, 7, max(7, $rowNumber - 1), count($cashbookHeaders));
    cashExcelMoneyFormat($cashbook, 'I7:K' . max(7, $rowNumber - 1));
    cashExcelSetWidths($cashbook, ['A'=>13,'B'=>24,'C'=>29,'D'=>11,'E'=>24,'F'=>28,'G'=>38,'H'=>22,'I'=>15,'J'=>15,'K'=>16,'L'=>20,'M'=>18,'N'=>18,'O'=>27,'P'=>20]);

    // Daily activity.
    $dailySheet = $spreadsheet->createSheet();
    $dailySheet->setTitle('Daily Activity');
    $dailyHeaders = ['Date', 'Transactions', 'Usable Increase', 'Usable Reduction', 'Net Usable Movement', 'Closing Usable Balance'];
    cashExcelBrandSheet($dailySheet, 'DAILY CASH ACTIVITY', $accountLabel, $periodLabel, count($dailyHeaders), 6, true);
    $dailySheet->fromArray($dailyHeaders, null, 'A6');
    $rowNumber = 7;
    foreach ($report['daily_activity'] as $row) {
        $dailySheet->fromArray([$row['transaction_date'], $row['transaction_count'], $row['usable_in'] ?? $row['cash_in'], $row['usable_out'] ?? $row['cash_out'], $row['net_usable_movement'] ?? $row['net_movement'], $row['closing_usable_balance'] ?? $row['closing_balance']], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($dailySheet, 7, max(7, $rowNumber - 1), count($dailyHeaders));
    cashExcelMoneyFormat($dailySheet, 'C7:F' . max(7, $rowNumber - 1));
    cashExcelSetWidths($dailySheet, ['A'=>15,'B'=>14,'C'=>18,'D'=>18,'E'=>18,'F'=>22]);

    // IOU register.
    $iouSheet = $spreadsheet->createSheet();
    $iouSheet->setTitle('IOU Register');
    $iouHeaders = ['Date', 'IOU Reference', 'Recipient', 'Reason', 'Category', 'Advanced', 'Actual Spent', 'Cash Returned', 'Reimbursement', 'Outstanding', 'Cash Return Due', 'Reimbursement Due', 'Due Date', 'Status', 'Receipt Status'];
    cashExcelBrandSheet($iouSheet, 'IOU RETIREMENT REGISTER', $accountLabel, $periodLabel, count($iouHeaders), 6, true);
    $iouSheet->fromArray($iouHeaders, null, 'A6');
    $rowNumber = 7;
    foreach ($report['ious'] as $iou) {
        $iouSheet->fromArray([
            $iou['transaction_date'], $iou['iou_reference'], $iou['recipient_name'], $iou['reason'], $iou['category_name'],
            $iou['amount_advanced'], $iou['actual_amount_spent'], $iou['amount_returned'], $iou['reimbursement_paid'],
            $iou['outstanding_amount'], $iou['cash_return_due'], $iou['reimbursement_due'], $iou['expected_retirement_date'],
            $iou['display_status'], $iou['receipt_status'],
        ], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($iouSheet, 7, max(7, $rowNumber - 1), count($iouHeaders));
    cashExcelMoneyFormat($iouSheet, 'F7:L' . max(7, $rowNumber - 1));
    cashExcelStatusStyle($iouSheet, 'N', 7, max(7, $rowNumber - 1));
    cashExcelSetWidths($iouSheet, ['A'=>13,'B'=>22,'C'=>24,'D'=>30,'E'=>20,'F'=>15,'G'=>15,'H'=>15,'I'=>15,'J'=>15,'K'=>16,'L'=>18,'M'=>14,'N'=>20,'O'=>18]);

    // Mutilated cash register.
    $mutilatedSheet = $spreadsheet->createSheet();
    $mutilatedSheet->setTitle('Mutilated Cash');
    $mutilatedSheet->getTabColor()->setRGB(CASH_REPORT_AMBER);
    $mutilatedHeaders = ['Discovered Date', 'Source Receipt', 'Received From', 'Receipt Amount', 'Linked Disbursement', 'Recipient', 'Mutilated Amount', 'Classification Reference', 'Status', 'Return / Replacement Date', 'Resolution', 'Bank Reference', 'Resolution Reference', 'Discovery Note', 'Resolution Note', 'Recorded By', 'Resolved By'];
    cashExcelBrandSheet($mutilatedSheet, 'MUTILATED CASH REGISTER', $accountLabel, $periodLabel, count($mutilatedHeaders), 6, true);
    $mutilatedSheet->fromArray($mutilatedHeaders, null, 'A6');
    $rowNumber = 7;
    foreach ($report['mutilated_cash'] as $record) {
        $mutilatedSheet->fromArray([
            $record['discovered_date'], $record['source_receipt_reference'], $record['source_receipt_person'], $record['source_receipt_amount'],
            $record['linked_disbursement_reference'], $record['recipient_name'], $record['amount'], $record['set_aside_reference'],
            $record['status'], $record['return_date'], $record['resolution_type'], $record['bank_reference'], $record['resolution_reference'],
            $record['note'], $record['resolution_note'], $record['discovered_by_email'], $record['resolved_by_email'],
        ], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($mutilatedSheet, 7, max(7, $rowNumber - 1), count($mutilatedHeaders));
    cashExcelMoneyFormat($mutilatedSheet, 'D7:D' . max(7, $rowNumber - 1));
    cashExcelMoneyFormat($mutilatedSheet, 'G7:G' . max(7, $rowNumber - 1));
    cashExcelStatusStyle($mutilatedSheet, 'I', 7, max(7, $rowNumber - 1));
    cashExcelSetWidths($mutilatedSheet, ['A'=>16,'B'=>25,'C'=>24,'D'=>18,'E'=>25,'F'=>24,'G'=>17,'H'=>25,'I'=>18,'J'=>20,'K'=>15,'L'=>22,'M'=>24,'N'=>34,'O'=>34,'P'=>27,'Q'=>27]);

    // Receipt register.
    $receiptSheet = $spreadsheet->createSheet();
    $receiptSheet->setTitle('Receipt Register');
    $receiptHeaders = ['Date', 'Transaction Reference', 'IOU Reference', 'Recipient', 'Document Type', 'Filename', 'MIME Type', 'Size (Bytes)', 'Uploaded By', 'Uploaded At', 'Status'];
    cashExcelBrandSheet($receiptSheet, 'SUPPORTING DOCUMENT REGISTER', $accountLabel, $periodLabel, count($receiptHeaders), 6, true);
    $receiptSheet->fromArray($receiptHeaders, null, 'A6');
    $rowNumber = 7;
    foreach ($report['receipts'] as $receipt) {
        $receiptSheet->fromArray([
            $receipt['transaction_date'], $receipt['transaction_reference'], $receipt['iou_reference'], $receipt['person_name'],
            $receipt['document_type'], $receipt['original_filename'], $receipt['mime_type'], $receipt['file_size'],
            $receipt['uploaded_by_email'], $receipt['created_at'], $receipt['status'],
        ], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($receiptSheet, 7, max(7, $rowNumber - 1), count($receiptHeaders));
    cashExcelStatusStyle($receiptSheet, 'K', 7, max(7, $rowNumber - 1));
    cashExcelSetWidths($receiptSheet, ['A'=>13,'B'=>25,'C'=>22,'D'=>24,'E'=>18,'F'=>36,'G'=>22,'H'=>15,'I'=>27,'J'=>20,'K'=>14]);

    // Daily closures.
    $closureSheet = $spreadsheet->createSheet();
    $closureSheet->setTitle('Daily Closures');
    $closureHeaders = ['Date', 'Opening Balance', 'Cash Received', 'Cash Returned', 'Cash Disbursed', 'Reimbursements', 'System Closing', 'Physical Cash', 'Difference', 'Status', 'Difference Note', 'Closed By', 'Closed At', 'Reopen Reason'];
    cashExcelBrandSheet($closureSheet, 'DAILY CASH CLOSING REGISTER', $accountLabel, $periodLabel, count($closureHeaders), 6, true);
    $closureSheet->fromArray($closureHeaders, null, 'A6');
    $rowNumber = 7;
    foreach ($report['daily_closures'] as $closure) {
        $closureSheet->fromArray([
            $closure['closure_date'], $closure['opening_balance'], $closure['cash_received'], $closure['cash_returned'],
            $closure['cash_disbursed'], $closure['reimbursements_paid'], $closure['system_closing_balance'],
            $closure['physical_cash_counted'], $closure['difference_amount'], $closure['status'], $closure['difference_note'],
            $closure['closed_by_email'], $closure['closed_at'], $closure['reopen_reason'],
        ], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($closureSheet, 7, max(7, $rowNumber - 1), count($closureHeaders));
    cashExcelMoneyFormat($closureSheet, 'B7:I' . max(7, $rowNumber - 1));
    cashExcelStatusStyle($closureSheet, 'J', 7, max(7, $rowNumber - 1));
    cashExcelSetWidths($closureSheet, ['A'=>13,'B'=>17,'C'=>16,'D'=>16,'E'=>17,'F'=>16,'G'=>17,'H'=>16,'I'=>14,'J'=>14,'K'=>36,'L'=>27,'M'=>20,'N'=>36]);

    // Expense analysis.
    $categorySheet = $spreadsheet->createSheet();
    $categorySheet->setTitle('Expense Analysis');
    cashExcelBrandSheet($categorySheet, 'EXPENSE CATEGORY ANALYSIS', $accountLabel, $periodLabel, 3, 6, false);
    $categorySheet->fromArray(['Category', 'Transactions', 'Amount'], null, 'A6');
    $rowNumber = 7;
    foreach ($report['category_summary'] as $row) {
        $categorySheet->fromArray([$row['category_name'], $row['transaction_count'], $row['amount']], null, 'A' . $rowNumber++);
    }
    cashExcelStyleRows($categorySheet, 7, max(7, $rowNumber - 1), 3);
    cashExcelMoneyFormat($categorySheet, 'C7:C' . max(7, $rowNumber - 1));
    cashExcelSetWidths($categorySheet, ['A'=>36,'B'=>16,'C'=>20]);
    }

    $spreadsheet->setActiveSheetIndex(0);
    $filename = $exportType === 'submission'
        ? ($startDate === $endDate
            ? 'Lambert-Daily-Cash-Report-' . $startDate . '.xlsx'
            : 'Lambert-Cash-Report-' . $startDate . '-to-' . $endDate . '.xlsx')
        : 'AcctLab-Cash-Position-' . $startDate . '-to-' . $endDate . '.xlsx';
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: private, no-store, max-age=0');
    header('X-Content-Type-Options: nosniff');
    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    $spreadsheet->disconnectWorksheets();
    exit;
} catch (Throwable $error) {
    cashHandleError($error, 'Unable to export the Cash Desk report.');
}
